[musofm]
title = "MusoFM"
url = "https://muso.fm"
entrySelector = ".channels-container .channel-box"
titleSelector = ".station-title-text"
linkSelector = ".station-title-text a"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
